package com.mottc.coze.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mottc.coze.bean.CozeUser;
import com.mottc.coze.bean.InviteMessage;

import com.mottc.coze.db.CozeUserDao;
import com.mottc.coze.db.InviteMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cozeUserDaoConfig;
    private final DaoConfig inviteMessageDaoConfig;

    private final CozeUserDao cozeUserDao;
    private final InviteMessageDao inviteMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cozeUserDaoConfig = daoConfigMap.get(CozeUserDao.class).clone();
        cozeUserDaoConfig.initIdentityScope(type);

        inviteMessageDaoConfig = daoConfigMap.get(InviteMessageDao.class).clone();
        inviteMessageDaoConfig.initIdentityScope(type);

        cozeUserDao = new CozeUserDao(cozeUserDaoConfig, this);
        inviteMessageDao = new InviteMessageDao(inviteMessageDaoConfig, this);

        registerDao(CozeUser.class, cozeUserDao);
        registerDao(InviteMessage.class, inviteMessageDao);
    }
    
    public void clear() {
        cozeUserDaoConfig.clearIdentityScope();
        inviteMessageDaoConfig.clearIdentityScope();
    }

    public CozeUserDao getCozeUserDao() {
        return cozeUserDao;
    }

    public InviteMessageDao getInviteMessageDao() {
        return inviteMessageDao;
    }

}
