package com.mottc.coze.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mottc.coze.bean.CozeUser;

import com.mottc.coze.db.CozeUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cozeUserDaoConfig;

    private final CozeUserDao cozeUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cozeUserDaoConfig = daoConfigMap.get(CozeUserDao.class).clone();
        cozeUserDaoConfig.initIdentityScope(type);

        cozeUserDao = new CozeUserDao(cozeUserDaoConfig, this);

        registerDao(CozeUser.class, cozeUserDao);
    }
    
    public void clear() {
        cozeUserDaoConfig.clearIdentityScope();
    }

    public CozeUserDao getCozeUserDao() {
        return cozeUserDao;
    }

}
